# Generated by Django 3.0.2 on 2020-01-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your experiment.', max_length=10000, unique=True)),
                ('pop_size', models.IntegerField(help_text='How large is the population?')),
                ('vacc_percentage', models.FloatField(help_text='What percentage of the population is initially vaccinated against the virus?')),
                ('mortality_rate', models.FloatField(help_text='How likely is a patient infected with the virus likely to succumb?Must be a percentage between 0.00 and 1.00.')),
                ('repro_rate', models.FloatField(help_text='How effective is the virus at spreading between individuals?Must be a percentage between 0.00 and 1.00.')),
                ('init_infected', models.IntegerField(help_text='At the beginning of the experiment, how many people in the population are infected with the virus?')),
                ('init_report', models.TextField(help_text='Summary of initial conditions.')),
                ('final_summary', models.TextField(help_text='Summary of what happened to the population over the entire experiment.')),
            ],
        ),
        migrations.CreateModel(
            name='TimeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(help_text='What time step is this TimeStep for?')),
                ('image', models.ImageField(help_text='Graph representing changes to the population during the TimeStep.', upload_to='images/')),
                ('description', models.TextField(help_text='What happened during this time step?')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this TimeStep was created. Auto-generated when the model saves, used for ordering.')),
                ('experiment', models.ForeignKey(help_text='The related Experiment model.', on_delete=django.db.models.deletion.CASCADE, to='simulator.Experiment')),
            ],
        ),
    ]
