# Generated by Django 3.0.2 on 2020-01-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_experiment_virus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='mortality_rate',
            new_name='mortality_chance',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='pop_size',
            new_name='population_size',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='repro_rate',
            new_name='reproductive_rate',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='vacc_percentage',
            new_name='vaccination_percent',
        ),
    ]
