# Generated by Django 3.0.2 on 2020-01-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20200115_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestep',
            name='description',
            field=models.TextField(help_text='Verbal summary of time step.'),
        ),
    ]
