# Generated by Django 3.0.2 on 2020-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_auto_20200116_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.CharField(help_text='Title of your experiment.', max_length=10000),
        ),
    ]
