# Generated by Django 3.0.2 on 2020-01-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_auto_20200117_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='final_summary',
            field=models.CharField(help_text='Summary of what happened to the population over the entire experiment.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='init_report',
            field=models.CharField(help_text='Summary of initial conditions.', max_length=10000),
        ),
    ]
