# Generated by Django 3.0.2 on 2020-01-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_auto_20200118_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='final_summary',
            field=models.TextField(help_text='Summary of what happened to the population over the entire experiment.'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='init_report',
            field=models.TextField(help_text='Summary of initial conditions.'),
        ),
    ]
