# Generated by Django 3.0.2 on 2020-01-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_auto_20200118_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestep',
            name='description',
        ),
        migrations.AddField(
            model_name='timestep',
            name='alive',
            field=models.IntegerField(default=1, help_text='People who are currently alive.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='current_infected',
            field=models.IntegerField(default=1, help_text='People infected who are still alive in this step of the experiment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='dead',
            field=models.IntegerField(default=1, help_text='People thus far who have succumbed.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='total_infected',
            field=models.IntegerField(default=1, help_text='People who contracted the virus thus far in the experiment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='total_vaccinated',
            field=models.IntegerField(default=1, help_text='Amount of individuals who are now vaccinated in the population.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='uninfected',
            field=models.IntegerField(default=1, help_text='People who have not had any interaction with the virus.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='uninteracted',
            field=models.IntegerField(default=1, help_text='Alive people in the population who are both uninfected, not vaccinated.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestep',
            name='vaccinated_population',
            field=models.FloatField(default=1, help_text='Percentage of the overall population which is currently vaccinated.'),
            preserve_default=False,
        ),
    ]
