# Generated by Django 3.0.2 on 2020-01-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_remove_experiment_total_infected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestep',
            name='image',
        ),
    ]
