# Generated by Django 3.0.2 on 2020-01-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_remove_timestep_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestep',
            name='vaccinated_population',
        ),
    ]
